# efs-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi            # EFS는 자동 확장되므로 이 숫자는 형식적인 값입니다. 아무거나 적어도 무방합니다.
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany         # [핵심] 여러 파드가 동시에 읽고 쓸 수 있는 권한 (RWX)
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: "fs-0dec0a8d180df08e4"  # 여기에 AWS EFS 파일 시스템 ID를 적어주세요!