# efs-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim           # 이름을 deploy.yaml 에서 호출할 예정
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc # efs 의 main.tf 에 정의한 storage class name 일치시키기 
  resources:
    requests:
      storage: 5Gi   # 형식만 맞춰주는것이고 숫자는 의미 없음 (크기는 저장한 만큼 동적으로 늘어남)